//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kin.Identity.Repository.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SocialProvider
    {
        public SocialProvider()
        {
            this.UserSocialConnections = new HashSet<UserSocialConnection>();
        }
    
        public int SocialProviderId { get; set; }
        public string Name { get; set; }
        public string Uri { get; set; }
        public bool IsIdentityProvider { get; set; }
        public bool IsSocial { get; set; }
        public string AssertionType { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateLastUpdated { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
        public byte[] ts { get; set; }
    
        public virtual ICollection<UserSocialConnection> UserSocialConnections { get; set; }
    }
}
