//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kin.Identity.Repository.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSocialConnection
    {
        public int UserId { get; set; }
        public int SocialProviderId { get; set; }
        public string ProviderIdentifier { get; set; }
        public string ProviderNameIdentifier { get; set; }
        public bool IsIdentity { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateLastUpdated { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
        public byte[] ts { get; set; }
    
        public virtual SocialProvider SocialProvider { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
