//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kin.Identity.Repository.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.UserSocialConnections = new HashSet<UserSocialConnection>();
        }
    
        public int UserId { get; set; }
        public string Username { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Bio { get; set; }
        public string Website { get; set; }
        public bool IsPrivate { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateLastUpdated { get; set; }
        public byte[] ts { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<UserSocialConnection> UserSocialConnections { get; set; }
    }
}
